name: Shopify CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main
    
jobs:
          
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#2D87E2'
        SLACK_ICON: https://github.com/Shopify/shopify.github.com/blob/master/images/github.svg?size=48
        SLACK_MESSAGE: 'Change Made to Live Site -- ${{ github.event.repository.name }}'
        SLACK_TITLE: Admin Panel or Git Change made
        SLACK_USERNAME: Shopify CI
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: ''

         
  
